#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-openstackclient
Version  : 1.7.1
Release  : 17
URL      : http://tarballs.openstack.org/python-openstackclient/python-openstackclient-1.7.1.tar.gz
Source0  : http://tarballs.openstack.org/python-openstackclient/python-openstackclient-1.7.1.tar.gz
Summary  : OpenStack Command-line Client
Group    : Development/Tools
License  : Apache-2.0
Requires: python-openstackclient-bin
Requires: python-openstackclient-python
BuildRequires : Babel-python
BuildRequires : Jinja2-python
BuildRequires : Pygments-python
BuildRequires : Sphinx-python
BuildRequires : WebOb-python
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : cliff-python
BuildRequires : cliff-tablib-python
BuildRequires : cmd2-python
BuildRequires : coverage-python
BuildRequires : cryptography-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : enum34-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : fixtures-python
BuildRequires : flake8-python
BuildRequires : funcsigs-python
BuildRequires : hacking-python
BuildRequires : idna-python
BuildRequires : ipaddress-python
BuildRequires : iso8601-python
BuildRequires : jsonpatch-python
BuildRequires : jsonpointer-python
BuildRequires : jsonschema-python
BuildRequires : linecache2-python
BuildRequires : markupsafe-python
BuildRequires : mccabe-python
BuildRequires : mox3-python
BuildRequires : msgpack-python-python
BuildRequires : netaddr-python
BuildRequires : netifaces-python
BuildRequires : os-client-config-python
BuildRequires : oslo.config-python
BuildRequires : oslo.i18n-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pep8-python
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : prettytable-python
BuildRequires : py-python
BuildRequires : pyOpenSSL-python
BuildRequires : pyasn1-python
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pyflakes-python
BuildRequires : pyparsing-python
BuildRequires : pytest
BuildRequires : python-cinderclient-python
BuildRequires : python-dev
BuildRequires : python-glanceclient-python
BuildRequires : python-keystoneclient-python
BuildRequires : python-mimeparse-python
BuildRequires : python-mock
BuildRequires : python-neutronclient-python
BuildRequires : python-novaclient-python
BuildRequires : python-subunit-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : simplejson-python
BuildRequires : six
BuildRequires : six-python
BuildRequires : stevedore-python
BuildRequires : tablib-python
BuildRequires : testrepository-python
BuildRequires : testscenarios-python
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv
BuildRequires : warlock-python
Patch1: 0001-Enable-parsing-image-name-as-image-ID.patch

%description
===============
OpenStackClient
===============
OpenStackClient (aka OSC) is a command-line client for OpenStack that brings
the command set for Compute, Identity, Image, Object Store and Volume APIs
together in a single shell with a uniform command structure.

%package bin
Summary: bin components for the python-openstackclient package.
Group: Binaries

%description bin
bin components for the python-openstackclient package.


%package python
Summary: python components for the python-openstackclient package.
Group: Default
Requires: Babel-python
Requires: cliff-python
Requires: cliff-tablib-python
Requires: os-client-config-python
Requires: oslo.i18n-python
Requires: oslo.utils-python
Requires: python-cinderclient-python
Requires: python-glanceclient-python
Requires: python-keystoneclient-python
Requires: python-neutronclient-python
Requires: python-novaclient-python
Requires: requests-python
Requires: six-python

%description python
python components for the python-openstackclient package.


%prep
%setup -q -n python-openstackclient-1.7.1
%patch1 -p1

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/openstack

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
